version: "3"

services:
  app:
    build:
      context: .
    container_name: bot-container
    ports:
      - "443:443"
    tty: true
    volumes:
      - "/root/asseri/config:/asseri/config"
      - "/root/asseri/log:/asseri/log"
